version: 2

models:

  - name: meat_prices_summary_per_year
    columns:
      - name: year
        tests:
          - not_null
      - name: max_price
        tests:
          - not_null
      - name: average_price
        tests:
          - not_null
